package com.example.springbootdemo.dao.mapper;

import com.example.springbootdemo.dao.domain.AccountingProject;
import com.example.springbootdemo.dao.domain.AccountingProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountingProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting_project
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    long countByExample(AccountingProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting_project
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    int deleteByExample(AccountingProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting_project
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting_project
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    int insert(AccountingProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting_project
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    int insertSelective(AccountingProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting_project
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    List<AccountingProject> selectByExample(AccountingProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting_project
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    AccountingProject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting_project
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    int updateByExampleSelective(@Param("record") AccountingProject record, @Param("example") AccountingProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting_project
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    int updateByExample(@Param("record") AccountingProject record, @Param("example") AccountingProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting_project
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    int updateByPrimaryKeySelective(AccountingProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting_project
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    int updateByPrimaryKey(AccountingProject record);
}