package com.example.springbootdemo.dao.domain;

import java.math.BigDecimal;
import java.util.Date;

public class AccountInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.id
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_id
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.user_id
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.name
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.phone
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_balance
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    private BigDecimal accountBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account_type
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    private Integer accountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.gb_code
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    private String gbCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.ctime
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.mtime
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.id
     *
     * @return the value of account_info.id
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.id
     *
     * @param id the value for account_info.id
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_id
     *
     * @return the value of account_info.account_id
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_id
     *
     * @param accountId the value for account_info.account_id
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.user_id
     *
     * @return the value of account_info.user_id
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.user_id
     *
     * @param userId the value for account_info.user_id
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.name
     *
     * @return the value of account_info.name
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.name
     *
     * @param name the value for account_info.name
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.phone
     *
     * @return the value of account_info.phone
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.phone
     *
     * @param phone the value for account_info.phone
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_balance
     *
     * @return the value of account_info.account_balance
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public BigDecimal getAccountBalance() {
        return accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_balance
     *
     * @param accountBalance the value for account_info.account_balance
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public void setAccountBalance(BigDecimal accountBalance) {
        this.accountBalance = accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account_type
     *
     * @return the value of account_info.account_type
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account_type
     *
     * @param accountType the value for account_info.account_type
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.gb_code
     *
     * @return the value of account_info.gb_code
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public String getGbCode() {
        return gbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.gb_code
     *
     * @param gbCode the value for account_info.gb_code
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public void setGbCode(String gbCode) {
        this.gbCode = gbCode == null ? null : gbCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.ctime
     *
     * @return the value of account_info.ctime
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.ctime
     *
     * @param ctime the value for account_info.ctime
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.mtime
     *
     * @return the value of account_info.mtime
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.mtime
     *
     * @param mtime the value for account_info.mtime
     *
     * @mbg.generated Sun Feb 20 13:25:13 CST 2022
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}