package com.example.springbootdemo.dao.domain;

import java.math.BigDecimal;
import java.util.Date;

public class AccountingProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.project_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.is_start_work
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Integer isStartWork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.owner_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private String ownerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.project_status
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Integer projectStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.project_address
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private String projectAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.project_address_cipher
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private String projectAddressCipher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.project_address_assist
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private String projectAddressAssist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.latest_complete_node_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Long latestCompleteNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.brand_type
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Integer brandType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.valuation_type
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Integer valuationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.price_rule_type
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Integer priceRuleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.grads_price_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Long gradsPriceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.tax_category
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal taxCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.reality_area_price
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal realityAreaPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.water_electricity_area_price
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal waterElectricityAreaPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.individuation_settlement_ratio
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Integer individuationSettlementRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.contract_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal contractAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.fix_cardinal_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal fixCardinalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.variable_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal variableAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.variable_cardinal_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal variableCardinalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.reality_area
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal realityArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.reality_area_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal realityAreaAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.water_electricity_area_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal waterElectricityAreaAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.dismantle_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal dismantleAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.individuation_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal individuationAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.fix_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Long fixRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.float_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Long floatRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.variable_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Long variableRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.quality_calculation_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Long qualityCalculationRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.satisfaction_calculation_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Long satisfactionCalculationRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.project_create_time
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Date projectCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.finish_work_time
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Date finishWorkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.start_work_time
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Date startWorkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.ingredients_all_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal ingredientsAllAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.installer_package_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal installerPackageAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.installer_manage_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal installerManageAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.installer_extra_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private BigDecimal installerExtraAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.gb_code
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Integer gbCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.ctime
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.mtime
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Date mtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.city_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.district_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private String districtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.package_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Long packageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.package_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private String packageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting_project.deliver_model
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    private Integer deliverModel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.id
     *
     * @return the value of accounting_project.id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.id
     *
     * @param id the value for accounting_project.id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.project_id
     *
     * @return the value of accounting_project.project_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.project_id
     *
     * @param projectId the value for accounting_project.project_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.is_start_work
     *
     * @return the value of accounting_project.is_start_work
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Integer getIsStartWork() {
        return isStartWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.is_start_work
     *
     * @param isStartWork the value for accounting_project.is_start_work
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setIsStartWork(Integer isStartWork) {
        this.isStartWork = isStartWork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.owner_name
     *
     * @return the value of accounting_project.owner_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.owner_name
     *
     * @param ownerName the value for accounting_project.owner_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.project_status
     *
     * @return the value of accounting_project.project_status
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Integer getProjectStatus() {
        return projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.project_status
     *
     * @param projectStatus the value for accounting_project.project_status
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setProjectStatus(Integer projectStatus) {
        this.projectStatus = projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.project_address
     *
     * @return the value of accounting_project.project_address
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public String getProjectAddress() {
        return projectAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.project_address
     *
     * @param projectAddress the value for accounting_project.project_address
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setProjectAddress(String projectAddress) {
        this.projectAddress = projectAddress == null ? null : projectAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.project_address_cipher
     *
     * @return the value of accounting_project.project_address_cipher
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public String getProjectAddressCipher() {
        return projectAddressCipher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.project_address_cipher
     *
     * @param projectAddressCipher the value for accounting_project.project_address_cipher
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setProjectAddressCipher(String projectAddressCipher) {
        this.projectAddressCipher = projectAddressCipher == null ? null : projectAddressCipher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.project_address_assist
     *
     * @return the value of accounting_project.project_address_assist
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public String getProjectAddressAssist() {
        return projectAddressAssist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.project_address_assist
     *
     * @param projectAddressAssist the value for accounting_project.project_address_assist
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setProjectAddressAssist(String projectAddressAssist) {
        this.projectAddressAssist = projectAddressAssist == null ? null : projectAddressAssist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.latest_complete_node_id
     *
     * @return the value of accounting_project.latest_complete_node_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Long getLatestCompleteNodeId() {
        return latestCompleteNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.latest_complete_node_id
     *
     * @param latestCompleteNodeId the value for accounting_project.latest_complete_node_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setLatestCompleteNodeId(Long latestCompleteNodeId) {
        this.latestCompleteNodeId = latestCompleteNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.brand_type
     *
     * @return the value of accounting_project.brand_type
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Integer getBrandType() {
        return brandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.brand_type
     *
     * @param brandType the value for accounting_project.brand_type
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setBrandType(Integer brandType) {
        this.brandType = brandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.valuation_type
     *
     * @return the value of accounting_project.valuation_type
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Integer getValuationType() {
        return valuationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.valuation_type
     *
     * @param valuationType the value for accounting_project.valuation_type
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setValuationType(Integer valuationType) {
        this.valuationType = valuationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.price_rule_type
     *
     * @return the value of accounting_project.price_rule_type
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Integer getPriceRuleType() {
        return priceRuleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.price_rule_type
     *
     * @param priceRuleType the value for accounting_project.price_rule_type
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setPriceRuleType(Integer priceRuleType) {
        this.priceRuleType = priceRuleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.grads_price_id
     *
     * @return the value of accounting_project.grads_price_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Long getGradsPriceId() {
        return gradsPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.grads_price_id
     *
     * @param gradsPriceId the value for accounting_project.grads_price_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setGradsPriceId(Long gradsPriceId) {
        this.gradsPriceId = gradsPriceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.tax_category
     *
     * @return the value of accounting_project.tax_category
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getTaxCategory() {
        return taxCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.tax_category
     *
     * @param taxCategory the value for accounting_project.tax_category
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setTaxCategory(BigDecimal taxCategory) {
        this.taxCategory = taxCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.reality_area_price
     *
     * @return the value of accounting_project.reality_area_price
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getRealityAreaPrice() {
        return realityAreaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.reality_area_price
     *
     * @param realityAreaPrice the value for accounting_project.reality_area_price
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setRealityAreaPrice(BigDecimal realityAreaPrice) {
        this.realityAreaPrice = realityAreaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.water_electricity_area_price
     *
     * @return the value of accounting_project.water_electricity_area_price
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getWaterElectricityAreaPrice() {
        return waterElectricityAreaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.water_electricity_area_price
     *
     * @param waterElectricityAreaPrice the value for accounting_project.water_electricity_area_price
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setWaterElectricityAreaPrice(BigDecimal waterElectricityAreaPrice) {
        this.waterElectricityAreaPrice = waterElectricityAreaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.individuation_settlement_ratio
     *
     * @return the value of accounting_project.individuation_settlement_ratio
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Integer getIndividuationSettlementRatio() {
        return individuationSettlementRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.individuation_settlement_ratio
     *
     * @param individuationSettlementRatio the value for accounting_project.individuation_settlement_ratio
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setIndividuationSettlementRatio(Integer individuationSettlementRatio) {
        this.individuationSettlementRatio = individuationSettlementRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.contract_amount
     *
     * @return the value of accounting_project.contract_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getContractAmount() {
        return contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.contract_amount
     *
     * @param contractAmount the value for accounting_project.contract_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setContractAmount(BigDecimal contractAmount) {
        this.contractAmount = contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.fix_cardinal_amount
     *
     * @return the value of accounting_project.fix_cardinal_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getFixCardinalAmount() {
        return fixCardinalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.fix_cardinal_amount
     *
     * @param fixCardinalAmount the value for accounting_project.fix_cardinal_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setFixCardinalAmount(BigDecimal fixCardinalAmount) {
        this.fixCardinalAmount = fixCardinalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.variable_amount
     *
     * @return the value of accounting_project.variable_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getVariableAmount() {
        return variableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.variable_amount
     *
     * @param variableAmount the value for accounting_project.variable_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setVariableAmount(BigDecimal variableAmount) {
        this.variableAmount = variableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.variable_cardinal_amount
     *
     * @return the value of accounting_project.variable_cardinal_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getVariableCardinalAmount() {
        return variableCardinalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.variable_cardinal_amount
     *
     * @param variableCardinalAmount the value for accounting_project.variable_cardinal_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setVariableCardinalAmount(BigDecimal variableCardinalAmount) {
        this.variableCardinalAmount = variableCardinalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.reality_area
     *
     * @return the value of accounting_project.reality_area
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getRealityArea() {
        return realityArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.reality_area
     *
     * @param realityArea the value for accounting_project.reality_area
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setRealityArea(BigDecimal realityArea) {
        this.realityArea = realityArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.reality_area_amount
     *
     * @return the value of accounting_project.reality_area_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getRealityAreaAmount() {
        return realityAreaAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.reality_area_amount
     *
     * @param realityAreaAmount the value for accounting_project.reality_area_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setRealityAreaAmount(BigDecimal realityAreaAmount) {
        this.realityAreaAmount = realityAreaAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.water_electricity_area_amount
     *
     * @return the value of accounting_project.water_electricity_area_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getWaterElectricityAreaAmount() {
        return waterElectricityAreaAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.water_electricity_area_amount
     *
     * @param waterElectricityAreaAmount the value for accounting_project.water_electricity_area_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setWaterElectricityAreaAmount(BigDecimal waterElectricityAreaAmount) {
        this.waterElectricityAreaAmount = waterElectricityAreaAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.dismantle_amount
     *
     * @return the value of accounting_project.dismantle_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getDismantleAmount() {
        return dismantleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.dismantle_amount
     *
     * @param dismantleAmount the value for accounting_project.dismantle_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setDismantleAmount(BigDecimal dismantleAmount) {
        this.dismantleAmount = dismantleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.individuation_amount
     *
     * @return the value of accounting_project.individuation_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getIndividuationAmount() {
        return individuationAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.individuation_amount
     *
     * @param individuationAmount the value for accounting_project.individuation_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setIndividuationAmount(BigDecimal individuationAmount) {
        this.individuationAmount = individuationAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.fix_rule_id
     *
     * @return the value of accounting_project.fix_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Long getFixRuleId() {
        return fixRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.fix_rule_id
     *
     * @param fixRuleId the value for accounting_project.fix_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setFixRuleId(Long fixRuleId) {
        this.fixRuleId = fixRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.float_rule_id
     *
     * @return the value of accounting_project.float_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Long getFloatRuleId() {
        return floatRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.float_rule_id
     *
     * @param floatRuleId the value for accounting_project.float_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setFloatRuleId(Long floatRuleId) {
        this.floatRuleId = floatRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.variable_rule_id
     *
     * @return the value of accounting_project.variable_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Long getVariableRuleId() {
        return variableRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.variable_rule_id
     *
     * @param variableRuleId the value for accounting_project.variable_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setVariableRuleId(Long variableRuleId) {
        this.variableRuleId = variableRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.quality_calculation_rule_id
     *
     * @return the value of accounting_project.quality_calculation_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Long getQualityCalculationRuleId() {
        return qualityCalculationRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.quality_calculation_rule_id
     *
     * @param qualityCalculationRuleId the value for accounting_project.quality_calculation_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setQualityCalculationRuleId(Long qualityCalculationRuleId) {
        this.qualityCalculationRuleId = qualityCalculationRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.satisfaction_calculation_rule_id
     *
     * @return the value of accounting_project.satisfaction_calculation_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Long getSatisfactionCalculationRuleId() {
        return satisfactionCalculationRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.satisfaction_calculation_rule_id
     *
     * @param satisfactionCalculationRuleId the value for accounting_project.satisfaction_calculation_rule_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setSatisfactionCalculationRuleId(Long satisfactionCalculationRuleId) {
        this.satisfactionCalculationRuleId = satisfactionCalculationRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.project_create_time
     *
     * @return the value of accounting_project.project_create_time
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Date getProjectCreateTime() {
        return projectCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.project_create_time
     *
     * @param projectCreateTime the value for accounting_project.project_create_time
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setProjectCreateTime(Date projectCreateTime) {
        this.projectCreateTime = projectCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.finish_work_time
     *
     * @return the value of accounting_project.finish_work_time
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Date getFinishWorkTime() {
        return finishWorkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.finish_work_time
     *
     * @param finishWorkTime the value for accounting_project.finish_work_time
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setFinishWorkTime(Date finishWorkTime) {
        this.finishWorkTime = finishWorkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.start_work_time
     *
     * @return the value of accounting_project.start_work_time
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Date getStartWorkTime() {
        return startWorkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.start_work_time
     *
     * @param startWorkTime the value for accounting_project.start_work_time
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setStartWorkTime(Date startWorkTime) {
        this.startWorkTime = startWorkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.ingredients_all_amount
     *
     * @return the value of accounting_project.ingredients_all_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getIngredientsAllAmount() {
        return ingredientsAllAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.ingredients_all_amount
     *
     * @param ingredientsAllAmount the value for accounting_project.ingredients_all_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setIngredientsAllAmount(BigDecimal ingredientsAllAmount) {
        this.ingredientsAllAmount = ingredientsAllAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.installer_package_amount
     *
     * @return the value of accounting_project.installer_package_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getInstallerPackageAmount() {
        return installerPackageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.installer_package_amount
     *
     * @param installerPackageAmount the value for accounting_project.installer_package_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setInstallerPackageAmount(BigDecimal installerPackageAmount) {
        this.installerPackageAmount = installerPackageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.installer_manage_amount
     *
     * @return the value of accounting_project.installer_manage_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getInstallerManageAmount() {
        return installerManageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.installer_manage_amount
     *
     * @param installerManageAmount the value for accounting_project.installer_manage_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setInstallerManageAmount(BigDecimal installerManageAmount) {
        this.installerManageAmount = installerManageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.installer_extra_amount
     *
     * @return the value of accounting_project.installer_extra_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public BigDecimal getInstallerExtraAmount() {
        return installerExtraAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.installer_extra_amount
     *
     * @param installerExtraAmount the value for accounting_project.installer_extra_amount
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setInstallerExtraAmount(BigDecimal installerExtraAmount) {
        this.installerExtraAmount = installerExtraAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.gb_code
     *
     * @return the value of accounting_project.gb_code
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Integer getGbCode() {
        return gbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.gb_code
     *
     * @param gbCode the value for accounting_project.gb_code
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setGbCode(Integer gbCode) {
        this.gbCode = gbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.ctime
     *
     * @return the value of accounting_project.ctime
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.ctime
     *
     * @param ctime the value for accounting_project.ctime
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.mtime
     *
     * @return the value of accounting_project.mtime
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.mtime
     *
     * @param mtime the value for accounting_project.mtime
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.city_name
     *
     * @return the value of accounting_project.city_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.city_name
     *
     * @param cityName the value for accounting_project.city_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.district_name
     *
     * @return the value of accounting_project.district_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.district_name
     *
     * @param districtName the value for accounting_project.district_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.package_id
     *
     * @return the value of accounting_project.package_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Long getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.package_id
     *
     * @param packageId the value for accounting_project.package_id
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setPackageId(Long packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.package_name
     *
     * @return the value of accounting_project.package_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.package_name
     *
     * @param packageName the value for accounting_project.package_name
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting_project.deliver_model
     *
     * @return the value of accounting_project.deliver_model
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public Integer getDeliverModel() {
        return deliverModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting_project.deliver_model
     *
     * @param deliverModel the value for accounting_project.deliver_model
     *
     * @mbg.generated Fri Feb 11 16:25:02 CST 2022
     */
    public void setDeliverModel(Integer deliverModel) {
        this.deliverModel = deliverModel;
    }
}