package com.example.springbootdemo.dao.domain;

public class OrderInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.sku_id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    private Integer skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.qty
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    private Integer qty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.sku_id
     *
     * @return the value of order_info.sku_id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.sku_id
     *
     * @param skuId the value for order_info.sku_id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.qty
     *
     * @return the value of order_info.qty
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.qty
     *
     * @param qty the value for order_info.qty
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }
}