package com.example.springbootdemo.dao.domain;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.sku_name
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    private String skuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.sku_id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    private Integer skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.qty
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    private Integer qty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.sku_name
     *
     * @return the value of stock.sku_name
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.sku_name
     *
     * @param skuName the value for stock.sku_name
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.sku_id
     *
     * @return the value of stock.sku_id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.sku_id
     *
     * @param skuId the value for stock.sku_id
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.qty
     *
     * @return the value of stock.qty
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.qty
     *
     * @param qty the value for stock.qty
     *
     * @mbg.generated Fri Jun 10 10:04:57 CST 2022
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }
}